#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

rm -f airfoil.geo
rm -f airfoil.msh
rm -f foam.log
rm -rf constant/polyMesh

rm -rf *[1-9]*
rm -f log.* 2>/dev/null

#------------------------------------------------------------------------------
